INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Aberdeen');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Armagh');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Bangor');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Bath');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Belfast');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Birmingham');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Bradford');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Brighton and Hove');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Bristol');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Cambridge');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Canterbury');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Cardiff');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Carlisle');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Chester');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Chichester');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'City of London');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Coventry');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Derby');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Dundee');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Durham');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Edinburgh');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Ely');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Exeter');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Glasgow');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Gloucester');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Hereford');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Inverness');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Kingston upon Hull');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Lancaster');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Leeds');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Leicester');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Lichfield');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Lincoln');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Lisburn');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Liverpool');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Londonderry');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Manchester');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Newcastle upon Tyne');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Newport');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Newry');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Norwich');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Nottingham');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Oxford');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Peterborough');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Plymouth');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Portsmouth');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Preston');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Ripon');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Salford');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Salisbury');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Sheffield');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Southampton');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'St Albans');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'St Davids');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Stirling');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Stoke-on-Trent');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Sunderland');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Swansea');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Truro');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Wakefield');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Wells');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Westminster');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Winchester');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Wolverhampton');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'Worcester');
INSERT INTO system.cities (id, city) VALUES (nextval('system.cities_id_seq'),'York');


