INSERT INTO ps_network.applications(id, name, code, description, is_active, country, city, information, is_hub, is_partner) VALUES (2, 'Fundación Colombia', 'fcolapp', 'Aplicación de fundación Colombia', true, 49, null, null, true, false);
INSERT INTO ps_network.applications(id, name, code, description, is_active, country, city, information, is_hub, is_partner) VALUES (3, 'Fundación Argentina', 'fargapp', 'Aplicación de fundación Argentina', true, 12, null, null, true, false);
INSERT INTO ps_network.applications(id, name, code, description, is_active, country, city, information, is_hub, is_partner) VALUES (4, 'Fundación Sudafrica', 'fsudapp', 'Aplicación de fundación Sudafrica', true, 240, null, null, true, false);
INSERT INTO ps_network.applications(id, name, code, description, is_active, country, city, information, is_hub, is_partner) VALUES (5, 'Fundación Mexico', 'fmexapp', 'Aplicación de fundación Mexico', true, 145, null, null, true, false);
INSERT INTO ps_network.applications(id, name, code, description, is_active, country, city, information, is_hub, is_partner) VALUES (6, 'Fundación Reino Unido', 'fukapp', 'Aplicación de fundación Reino Unido', true, 76, null, null, true, false);

INSERT INTO ps_network.organizations(id, name, code, description, is_active, country, information, application_id) VALUES (2, 'Farmacenter', 'farorg', 'Organizacion para el uso de Farmacenter', true, 1, null, 1);
INSERT INTO ps_network.organizations(id, name, code, description, is_active, country, information, application_id) VALUES (3, 'Las Tacuaras', 'tacorg', 'Organizacion para el uso de Las Tacuaras', true, 1, null, 1);
INSERT INTO ps_network.organizations(id, name, code, description, is_active, country, information, application_id) VALUES (4, 'El mejor', 'mejororg', 'Organizacion para el uso de El mejor', true, 1, null, 1);
INSERT INTO ps_network.organizations(id, name, code, description, is_active, country, information, application_id) VALUES (5, 'Iris', 'irisorg', 'Organizacion para el uso de Iris', true, 1, null, 1);
INSERT INTO ps_network.organizations(id, name, code, description, is_active, country, information, application_id) VALUES (6, 'Credicentro', 'crediorg', 'Organizacion para el uso de Credicentro', true, 1, null, 1);