INSERT INTO system.cities (id, city) VALUES (2,'Aberdeen');
INSERT INTO system.cities (id, city) VALUES (3,'Armagh');
INSERT INTO system.cities (id, city) VALUES (4,'Bangor');
INSERT INTO system.cities (id, city) VALUES (5,'Bath');
INSERT INTO system.cities (id, city) VALUES (6,'Belfast');
INSERT INTO system.cities (id, city) VALUES (7,'Birmingham');
INSERT INTO system.cities (id, city) VALUES (8,'Bradford');
INSERT INTO system.cities (id, city) VALUES (9,'Brighton and Hove');
INSERT INTO system.cities (id, city) VALUES (10,'Bristol');
INSERT INTO system.cities (id, city) VALUES (11,'Cambridge');
INSERT INTO system.cities (id, city) VALUES (12,'Canterbury');
INSERT INTO system.cities (id, city) VALUES (13,'Cardiff');
INSERT INTO system.cities (id, city) VALUES (14,'Carlisle');
INSERT INTO system.cities (id, city) VALUES (15,'Chester');
INSERT INTO system.cities (id, city) VALUES (16,'Chichester');
INSERT INTO system.cities (id, city) VALUES (17,'City of London');
INSERT INTO system.cities (id, city) VALUES (18,'Coventry');
INSERT INTO system.cities (id, city) VALUES (19,'Derby');
INSERT INTO system.cities (id, city) VALUES (20,'Dundee');
INSERT INTO system.cities (id, city) VALUES (21,'Durham');
INSERT INTO system.cities (id, city) VALUES (22,'Edinburgh');
INSERT INTO system.cities (id, city) VALUES (23,'Ely');
INSERT INTO system.cities (id, city) VALUES (24,'Exeter');
INSERT INTO system.cities (id, city) VALUES (25,'Glasgow');
INSERT INTO system.cities (id, city) VALUES (26,'Gloucester');
INSERT INTO system.cities (id, city) VALUES (27,'Hereford');
INSERT INTO system.cities (id, city) VALUES (28,'Inverness');
INSERT INTO system.cities (id, city) VALUES (29,'Kingston upon Hull');
INSERT INTO system.cities (id, city) VALUES (30,'Lancaster');
INSERT INTO system.cities (id, city) VALUES (31,'Leeds');
INSERT INTO system.cities (id, city) VALUES (32,'Leicester');
INSERT INTO system.cities (id, city) VALUES (33,'Lichfield');
INSERT INTO system.cities (id, city) VALUES (34,'Lincoln');
INSERT INTO system.cities (id, city) VALUES (35,'Lisburn');
INSERT INTO system.cities (id, city) VALUES (36,'Liverpool');
INSERT INTO system.cities (id, city) VALUES (37,'Londonderry');
INSERT INTO system.cities (id, city) VALUES (38,'Manchester');
INSERT INTO system.cities (id, city) VALUES (39,'Newcastle upon Tyne');
INSERT INTO system.cities (id, city) VALUES (40,'Newport');
INSERT INTO system.cities (id, city) VALUES (41,'Newry');
INSERT INTO system.cities (id, city) VALUES (42,'Norwich');
INSERT INTO system.cities (id, city) VALUES (43,'Nottingham');
INSERT INTO system.cities (id, city) VALUES (44,'Oxford');
INSERT INTO system.cities (id, city) VALUES (45,'Peterborough');
INSERT INTO system.cities (id, city) VALUES (46,'Plymouth');
INSERT INTO system.cities (id, city) VALUES (47,'Portsmouth');
INSERT INTO system.cities (id, city) VALUES (48,'Preston');
INSERT INTO system.cities (id, city) VALUES (49,'Ripon');
INSERT INTO system.cities (id, city) VALUES (50,'Salford');
INSERT INTO system.cities (id, city) VALUES (51,'Salisbury');
INSERT INTO system.cities (id, city) VALUES (52,'Sheffield');
INSERT INTO system.cities (id, city) VALUES (53,'Southampton');
INSERT INTO system.cities (id, city) VALUES (54,'St Albans');
INSERT INTO system.cities (id, city) VALUES (55,'St Davids');
INSERT INTO system.cities (id, city) VALUES (56,'Stirling');
INSERT INTO system.cities (id, city) VALUES (57,'Stoke-on-Trent');
INSERT INTO system.cities (id, city) VALUES (58,'Sunderland');
INSERT INTO system.cities (id, city) VALUES (59,'Swansea');
INSERT INTO system.cities (id, city) VALUES (60,'Truro');
INSERT INTO system.cities (id, city) VALUES (61,'Wakefield');
INSERT INTO system.cities (id, city) VALUES (62,'Wells');
INSERT INTO system.cities (id, city) VALUES (63,'Westminster');
INSERT INTO system.cities (id, city) VALUES (64,'Winchester');
INSERT INTO system.cities (id, city) VALUES (65,'Wolverhampton');
INSERT INTO system.cities (id, city) VALUES (66,'Worcester');
INSERT INTO system.cities (id, city) VALUES (67,'York');


