
alter table system.countries alter column country type character varying(50);

UPDATE system.countries 
SET 
	alfa_2_code = 'PY',
    numeric_code = '600',
    alfa_3_code = 'PRY'
WHERE id = 1;

INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (2,'AD','Andorra','020','AND');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (3,'AE','United Arab Emirates','784','ARE');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (4,'AF','Afghanistan','004','AFG');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (5,'AG','Antigua and Barbuda','028','ATG');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (6,'AI','Anguilla','660','AIA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (7,'AL','Albania','008','ALB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (8,'AM','Armenia','051','ARM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (9,'AN','Netherlands Antilles','530','ANT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (10,'AO','Angola','024','AGO');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (11,'AQ','Antarctica','010','ATA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (12,'AR','Argentina','032','ARG');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (13,'AS','American Samoa','016','ASM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (14,'AT','Austria','040','AUT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (15,'AU','Australia','036','AUS');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (16,'AW','Aruba','533','ABW');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (17,'AX','Aland Islands','248','ALA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (18,'AZ','Azerbaijan','031','AZE');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (19,'BA','Bosnia and Herzegovina','070','BIH');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (20,'BB','Barbados','052','BRB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (21,'BD','Bangladesh','050','BGD');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (22,'BE','Belgium','056','BEL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (23,'BF','Burkina Faso','854','BFA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (24,'BG','Bulgaria','100','BGR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (25,'BH','Bahrain','048','BHR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (26,'BI','Burundi','108','BDI');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (27,'BJ','Benin','204','BEN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (28,'BL','Saint-Barthélemy','652','BLM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (29,'BM','Bermuda','060','BMU');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (30,'BN','Brunei Darussalam','096','BRN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (31,'BO','Bolivia','068','BOL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (32,'BR','Brazil','076','BRA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (33,'BS','Bahamas','044','BHS');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (34,'BT','Bhutan','064','BTN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (35,'BV','Bouvet Island','074','BVT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (36,'BW','Botswana','072','BWA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (37,'BY','Belarus','112','BLR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (38,'BZ','Belize','084','BLZ');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (39,'CA','Canada','124','CAN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (40,'CC','Cocos (Keeling) Islands','166','CCK');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (41,'CF','Central African Republic','140','CAF');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (42,'CG','Congo','178','COG');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (43,'CH','Switzerland','756','CHE');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (44,'CI','Côte d''Ivoire','384','CIV');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (45,'CK','Cook Islands','184','COK');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (46,'CL','Chile','152','CHL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (47,'CM','Cameroon','120','CMR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (48,'CN','China','156','CHN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (49,'CO','Colombia','170','COL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (50,'CR','Costa Rica','188','CRI');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (51,'CU','Cuba','192','CUB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (52,'CV','Cabo Verde','132','CPV');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (53,'CX','Christmas Island','162','CXR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (54,'CY','Cyprus','196','CYP');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (55,'CZ','Czech Republic','203','CZE');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (56,'DE','Germany','276','DEU');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (57,'DJ','Djibouti','262','DJI');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (58,'DK','Denmark','208','DNK');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (59,'DM','Domínica','212','DMA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (60,'DO','Dominican Republic','214','DOM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (61,'DZ','Algeria','012','DZA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (62,'EC','Ecuador','218','ECU');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (63,'EE','Estonia','233','EST');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (64,'EG','Egypt','818','EGY');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (65,'EH','Western Sahara','732','ESH');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (66,'ER','Eritrea','232','ERI');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (67,'ES','Spain','724','ESP');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (68,'ET','Ethiopia','231','ETH');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (69,'FI','Finland','246','FIN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (70,'FJ','Fiji','242','FJI');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (71,'FK','Falkland Islands (Malvinas)','238','KLK');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (72,'FM','Micronesia','583','FSM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (73,'FO','Faroe Islands','234','FRO');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (74,'FR','France','250','FRA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (75,'GA','Gabon','266','GAB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (76,'GB','United Kingdom','826','GBR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (77,'GD','Grenada','308','GRD');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (78,'GE','Georgia','268','GEO');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (79,'GF','French Guiana','254','GUF');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (80,'GG','Guernsey','831','GGY');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (81,'GH','Ghana','288','GHA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (82,'GI','Gibraltar','292','GIB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (83,'GL','Greenland','304','GRL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (84,'GM','Gambia','270','GMB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (85,'GN','Guinea','324','GIN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (86,'GP','Guadeloupe','312','GLP');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (87,'GQ','Equatorial Guinea','226','GNQ');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (88,'GR','Greece','300','GRC');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (89,'GS','South Georgia and the South Sandwich Islands','239','SGS');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (90,'GT','Guatemala','320','GTM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (91,'GU','Guam','316','GUM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (92,'GW','Guinea-Bissau','624','GNB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (93,'GY','Guyana','328','GUY');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (94,'HK','Hong Kong','344','HKG');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (95,'HM','Heard and Mcdonald Islands','334','HMD');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (96,'HN','Honduras','340','HND');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (97,'HR','Croatia','191','HRV');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (98,'HT','Haiti','332','HTI');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (99,'HU','Hungary','348','HUN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (100,'ID','Indonesia','360','IDN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (101,'IE','Ireland','372','IRL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (102,'IL','Israel','376','ISR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (103,'IM','Isle of Man','833','IMN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (104,'IN','India','356','IND');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (105,'IO','British Indian Ocean Territory','086','IOT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (106,'IQ','Iraq','368','IRQ');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (107,'IR','Iran','364','IRN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (108,'IS','Iceland','352','ISL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (109,'IT','Italy','380','ITA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (110,'JE','Jersey','832','JEY');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (111,'JM','Jamaica','388','JAM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (112,'JO','Jordan','400','JOR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (113,'JP','Japan','392','JPN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (114,'KE','Kenya','404','KEN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (115,'KG','Kyrgyzstan','417','KGZ');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (116,'KH','Cambodia','116','KHM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (117,'KI','Kiribati','296','KIR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (118,'KM','Comoros','174','COM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (119,'KN','Saint Kitts and Nevis','659','KNA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (120,'KP','Korea (North)','408','PRK');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (121,'KR','Korea (South)','410','KOR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (122,'KW','Kuwait','414','KWT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (123,'KY','Cayman Islands','136','CYM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (124,'KZ','Kazakhstan','398','KAZ');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (125,'LA','Lao People''s Democratic Republic','418','LAO');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (126,'LB','Lebanon','422','LBN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (127,'LC','Saint Lucia','662','LCA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (128,'LI','Liechtenstein','438','LIE');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (129,'LK','Sri Lanka','144','LKA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (130,'LR','Liberia','430','LBR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (131,'LS','Lesotho','426','LSO');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (132,'LT','Lithuania','440','LTU');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (133,'LU','Luxembourg','442','LUX');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (134,'LV','Latvia','428','LVA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (135,'LY','Libya','434','LBY');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (136,'MA','Morocco','504','MAR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (137,'MC','Monaco','492','MCO');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (138,'MD','Moldova','498','MDA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (139,'ME','Montenegro','499','MNE');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (140,'MG','Madagascar','450','MDG');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (141,'MH','Marshall Islands','584','MHL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (142,'MK','Macedonia','807','MKD');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (143,'ML','Mali','466','MLI');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (144,'MM','Myanmar','104','MMR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (145,'MN','Mongolia','496','MNG');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (146,'MO','Macao','446','MAC');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (147,'MQ','Martinique','474','MTQ');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (148,'MR','Mauritania','478','MRT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (149,'MS','Montserrat','500','MSR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (150,'MT','Malta','470','MLT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (151,'MU','Mauritius','480','MUS');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (152,'MV','Maldives','462','MDV');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (153,'MW','Malawi','454','MWI');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (154,'MX','Mexico','484','MEX');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (155,'MY','Malaysia','458','MYS');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (156,'MZ','Mozambique','508','MOZ');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (157,'NA','Namibia','516','NAM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (158,'NC','New Caledonia','540','NCL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (159,'NE','Níger','562','NER');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (160,'NF','Norfolk Island','574','NFK');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (161,'NG','Nigeria','566','NGA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (162,'NI','Nicaragua','558','NIC');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (163,'NL','Netherlands','528','NLD');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (164,'NO','Norway','578','NOR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (165,'NP','Nepal','524','NPL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (166,'NR','Nauru','520','NRU');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (167,'NU','Niue','570','NIU');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (168,'NZ','New Zealand','554','NZL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (169,'OM','Oman','512','OMN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (170,'PA','Panama','591','PAN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (171,'PE','Peru','604','PER');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (172,'PF','French Polynesia','258','PYF');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (173,'PG','Papua New Guinea','598','PNG');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (174,'PH','Philippines','608','PHL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (175,'PK','Pakistan','586','PAK');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (176,'PL','Poland','616','POL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (177,'PM','Saint Pierre and Miquelon','666','SPM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (178,'PN','Pitcairn','612','PCN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (179,'PR','Puerto Rico','630','PRI');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (180,'PS','Palestine','275','PSE');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (181,'PT','Portugal','620','PRT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (182,'PW','Palau','585','PLW');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (183,'QA','Qatar','634','QAT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (184,'RE','Réunion','638','REU');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (185,'RO','Romania','642','ROU');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (186,'RS','Serbia','688','SRB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (187,'RU','Russia','643','RUS');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (188,'RW','Rwanda','646','RWA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (189,'SA','Saudi Arabia','682','SAU');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (190,'SB','Solomon Islands','090','SLB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (191,'SC','Seychelles','690','SYC');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (192,'SD','Sudan','736','SDN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (193,'SE','Sweden','752','SWE');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (194,'SG','Singapore','702','SGP');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (195,'SH','Saint Helena','654','SHN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (196,'SI','Slovenia','705','SVN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (197,'SJ','Svalbard and Jan Mayen Islands','744','SJM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (198,'SK','Slovakia','703','SVK');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (199,'SL','Sierra Leone','694','SLE');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (200,'SM','San Marino','674','SMR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (201,'SN','Senegal','686','SEN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (202,'SO','Somalia','706','SOM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (203,'SR','Suriname','740','SUR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (204,'ST','Sao Tome and Principe','678','STP');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (205,'SV','El Salvador','222','SLV');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (206,'SY','Syrian Arab Republic','760','SYR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (207,'SZ','Swaziland','748','SWZ');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (208,'TC','Turks and Caicos Islands','796','TCA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (209,'TD','Chad','148','TCD');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (210,'TF','French Southern Territories','260','ATF');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (211,'TG','Togo','768','TGO');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (212,'TH','Thailand','764','THA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (213,'TZ','Tanzania','834','TZA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (214,'TJ','Tajikistan','762','TJK');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (215,'TK','Tokelau','772','TKL');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (216,'TL','Timor-Leste','626','TLS');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (217,'TM','Turkmenistan','795','TKM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (218,'TN','Tunisia','788','TUN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (219,'TO','Tonga','776','TON');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (220,'TR','Turkey','792','TUR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (221,'TT','Trinidad and Tobago','780','TTO');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (222,'TV','Tuvalu','798','TUV');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (223,'TW','Taiwan','158','TWN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (224,'UA','Ukraine','804','UKR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (225,'UG','Uganda','800','UGA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (226,'US','United States of America','840','USA');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (227,'UY','Uruguay','858','URY');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (228,'UZ','Uzbekistan','860','UZB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (229,'VA','Holy See (Vatican City State)','336','VAT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (230,'VC','Saint Vincent and Grenadines','670','VCT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (231,'VE','Venezuela','862','VEN');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (232,'VG','British Virgin Islands','092','VGB');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (233,'VI','Virgin Islands (U.S.)','850','VIR');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (234,'VN','Viet Nam','704','VNM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (235,'VU','Vanuatu','548','VUT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (236,'WF','Wallis and Futuna Islands','876','WLF');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (237,'WS','Samoa','882','WSM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (238,'YE','Yemen','887','YEM');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (239,'YT','Mayotte','175','MYT');
INSERT INTO system.countries (id, alfa_2_code, country, numeric_code, alfa_3_code)  VALUES (240,'ZA','South Africa','710','ZAF');

