package py.org.fundacionparaguaya.pspserver.web.models;

/*
 * FP-PSP Server
 * A sample API to manage surveys
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * NewSurveyDefinition
 */

public class NewSurveyDefinition   {
    @JsonProperty("survey_schema")
    private SurveySchema surveySchema = null;

    @JsonProperty("survey_ui_schema")
    private Object surveyUiSchema = null;

    public NewSurveyDefinition surveySchema(SurveySchema surveySchema) {
        this.surveySchema = surveySchema;
        return this;
    }

    /**
     * Get surveySchema
     * @return surveySchema
     **/
    @JsonProperty("survey_schema")
    @ApiModelProperty(required = true, value = "")
    @NotNull
    public SurveySchema getSurveySchema() {
        return surveySchema;
    }

    public void setSurveySchema(SurveySchema surveySchema) {
        this.surveySchema = surveySchema;
    }

    public NewSurveyDefinition surveyUiSchema(Object surveyUiSchema) {
        this.surveyUiSchema = surveyUiSchema;
        return this;
    }

    /**
     * The UI SCHEMA definition of the survey, to be used on render
     * @return surveyUiSchema
     **/
    @JsonProperty("survey_ui_schema")
    @ApiModelProperty(required = true, value = "The UI SCHEMA definition of the survey, to be used on render")
    @NotNull
    public Object getSurveyUiSchema() {
        return surveyUiSchema;
    }

    public void setSurveyUiSchema(Object surveyUiSchema) {
        this.surveyUiSchema = surveyUiSchema;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NewSurveyDefinition newSurveyDefinition = (NewSurveyDefinition) o;
        return Objects.equals(this.surveySchema, newSurveyDefinition.surveySchema) &&
                Objects.equals(this.surveyUiSchema, newSurveyDefinition.surveyUiSchema);
    }

    @Override
    public int hashCode() {
        return Objects.hash(surveySchema, surveyUiSchema);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class NewSurveyDefinition {\n");

        sb.append("    surveySchema: ").append(toIndentedString(surveySchema)).append("\n");
        sb.append("    surveyUiSchema: ").append(toIndentedString(surveyUiSchema)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}

