package py.org.fundacionparaguaya.pspserver.web.models;
/*
 * FP-PSP Server
 * A sample API to manage surveys
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * SurveyDefinition
 */
public class SurveyDefinition   {
    @JsonProperty("survey_schema")
    private SurveySchema surveySchema = null;

    @JsonProperty("survey_ui_schema")
    private SurveyUiSchema surveyUiSchema = null;

    @JsonProperty("created_at")
    private String createdAt = null;

    @JsonProperty("last_modified_at")
    private String lastModifiedAt = null;

    @JsonProperty("user_created")
    private Integer userCreated = null;

    public SurveyDefinition surveySchema(SurveySchema surveySchema) {
        this.surveySchema = surveySchema;
        return this;
    }

    /**
     * Get surveySchema
     * @return surveySchema
     **/
    @JsonProperty("survey_schema")
    @ApiModelProperty(required = true, value = "")
    @NotNull
    public SurveySchema getSurveySchema() {
        return surveySchema;
    }

    public void setSurveySchema(SurveySchema surveySchema) {
        this.surveySchema = surveySchema;
    }

    public SurveyDefinition surveyUiSchema(SurveyUiSchema surveyUiSchema) {
        this.surveyUiSchema = surveyUiSchema;
        return this;
    }

    /**
     * Get surveyUiSchema
     * @return surveyUiSchema
     **/
    @JsonProperty("survey_ui_schema")
    @ApiModelProperty(required = true, value = "")
    @NotNull
    public SurveyUiSchema getSurveyUiSchema() {
        return surveyUiSchema;
    }

    public void setSurveyUiSchema(SurveyUiSchema surveyUiSchema) {
        this.surveyUiSchema = surveyUiSchema;
    }

    public SurveyDefinition createdAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }

    /**
     * [ISO 8601](https://es.wikipedia.org/wiki/ISO_8601) formatted creation date
     * @return createdAt
     **/
    @JsonProperty("created_at")
    @ApiModelProperty(value = "[ISO 8601](https://es.wikipedia.org/wiki/ISO_8601) formatted creation date")
    public String getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    public SurveyDefinition lastModifiedAt(String lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
        return this;
    }

    /**
     * [ISO 8601](https://es.wikipedia.org/wiki/ISO_8601) formatted modification date
     * @return lastModifiedAt
     **/
    @JsonProperty("last_modified_at")
    @ApiModelProperty(value = "[ISO 8601](https://es.wikipedia.org/wiki/ISO_8601) formatted modification date")
    public String getLastModifiedAt() {
        return lastModifiedAt;
    }

    public void setLastModifiedAt(String lastModifiedAt) {
        this.lastModifiedAt = lastModifiedAt;
    }

    public SurveyDefinition userCreated(Integer userCreated) {
        this.userCreated = userCreated;
        return this;
    }

    /**
     * the id of the user that created this definition
     * @return userCreated
     **/
    @JsonProperty("user_created")
    @ApiModelProperty(value = "the id of the user that created this definition")
    public Integer getUserCreated() {
        return userCreated;
    }

    public void setUserCreated(Integer userCreated) {
        this.userCreated = userCreated;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SurveyDefinition surveyDefinition = (SurveyDefinition) o;
        return Objects.equals(this.surveySchema, surveyDefinition.surveySchema) &&
                Objects.equals(this.surveyUiSchema, surveyDefinition.surveyUiSchema) &&
                Objects.equals(this.createdAt, surveyDefinition.createdAt) &&
                Objects.equals(this.lastModifiedAt, surveyDefinition.lastModifiedAt) &&
                Objects.equals(this.userCreated, surveyDefinition.userCreated);
    }

    @Override
    public int hashCode() {
        return Objects.hash(surveySchema, surveyUiSchema, createdAt, lastModifiedAt, userCreated);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SurveyDefinition {\n");

        sb.append("    surveySchema: ").append(toIndentedString(surveySchema)).append("\n");
        sb.append("    surveyUiSchema: ").append(toIndentedString(surveyUiSchema)).append("\n");
        sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
        sb.append("    lastModifiedAt: ").append(toIndentedString(lastModifiedAt)).append("\n");
        sb.append("    userCreated: ").append(toIndentedString(userCreated)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}


