package py.org.fundacionparaguaya.pspserver.web.models;
/*
 * FP-PSP Server
 * A sample API to manage surveys
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.common.base.Objects;
import com.google.common.collect.ForwardingMap;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;
import java.util.Map;

/**
 * The UI SCHEMA definition of the survey. Holds info clients would use to render the survey
 */
@ApiModel(description = "The UI SCHEMA definition of the survey. Holds info clients would use to render the survey")
public class SurveyUiSchema extends ForwardingMap<String, Property> {


    @JsonProperty("properties")
    private Map<String, Property> properties = null;

    @JsonProperty("ui:order")
    private List<String> uiOrder = null;


    @JsonProperty("ui:group:socioeconomics")
    private List<String> groupSocioEconomics = null;

    @JsonProperty("ui:group:indicators")
    private List<String> groupIndicators = null;


    public SurveyUiSchema properties(Map<String, Property> properties) {
        this.properties = properties;
        return this;
    }


    @ApiModelProperty("Specifies the order in which the fields should be rendererd in the UI")
    public List<String> getUiOrder() {
        return uiOrder;
    }

    public void setUiOrder(List<String> uiOrder) {
        this.uiOrder = uiOrder;
    }

    @Override
    protected Map<String, Property> delegate() {
        return this.properties;
    }


    @ApiModelProperty("Specifies which fields should be grouped as socio-economics in the UI")
    public List<String> getGroupSocioEconomics() {
        return groupSocioEconomics;
    }

    public void setGroupSocioEconomics(List<String> groupSocioEconomics) {
        this.groupSocioEconomics = groupSocioEconomics;
    }

    @ApiModelProperty("Specifies which fields should be grouped as indicators in the UI")
    public List<String> getGroupIndicators() {
        return groupIndicators;
    }

    public void setGroupIndicators(List<String> groupIndicators) {
        this.groupIndicators = groupIndicators;
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class SurveyUiSchema {\n");
        sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
        sb.append("    groupSocioEconomics: ").append(toIndentedString(groupSocioEconomics)).append("\n");
        sb.append("    groupIndicators: ").append(toIndentedString(groupIndicators)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        SurveyUiSchema that = (SurveyUiSchema) o;

        return Objects.equal(this.properties, that.properties) &&
                Objects.equal(this.uiOrder, that.uiOrder) &&
                Objects.equal(this.groupSocioEconomics, that.groupSocioEconomics) &&
                Objects.equal(this.groupIndicators, that.groupIndicators);
    }

    @Override
    public int hashCode() {
        return Objects.hashCode(properties, uiOrder, groupSocioEconomics, groupIndicators);
    }
}

